###Get/
GET http://localhost:5000
###register 
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"bella",
    "password":"123123"
}

###login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"bella",
    "password":"123123"
}
